name: CRON

on:
  push:
    paths:
    - '.github/**'
    - 'products.txt'
  schedule:
  - cron: '0 */2 * * *'

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 11.15
    - name: Install dependencies
      run: yarn install
    - name: Run price check
      env:
        SERVICE_ACCOUNTS: ${{ secrets.SERVICE_ACCOUNTS }}
      run: yarn start
